USE [CompanyDocumentStore]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ARITHABORT ON
GO

CREATE TABLE [dbo].[FileStore] AS FILETABLE ON [PRIMARY] FILESTREAM_ON [FileStreamGroup1]
WITH
(
FILETABLE_DIRECTORY = N'FileStore', FILETABLE_COLLATE_FILENAME = SQL_Latin1_General_CP1_CI_AS
)
GO