USE [CompanyDocumentStore]
GO

DROP TABLE IF EXISTS [dbo].[Sections]
GO

SET ANSI_NULLS ON
GO
 
SET QUOTED_IDENTIFIER ON
GO
 
CREATE TABLE [dbo].[Sections](
    [Id] int IDENTITY(1,1) NOT NULL,
    [SectionName] nvarchar(255) NOT NULL
	CONSTRAINT [PK_Sections] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO